name: Build

on:
  push:
    branches-ignore:
      - 'no-ci-**'
      - 'skip-ci-**'
  pull_request:
  workflow_dispatch:

jobs:
  PrepareMatrix:
    name: Prepare Matrix
    runs-on: ubuntu-latest
    outputs:
      platform_matrix: ${{ steps.prepare.outputs.platform_matrix }}
    steps:
      - name: Prepare rbfx matrix
        id: prepare
        uses: rokups/rbfx-temp/.github/actions/ci-prepare-matrix@rk/ci-reusable-workflow3
        with:
          artifact_platforms: 'windows,linux,macos,web'

  Build:
    name: ${{ matrix.ci_platform_tag }}
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    needs: [PrepareMatrix]
    runs-on: ${{ matrix.runs_on }}

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.PrepareMatrix.outputs.platform_matrix) }}

    steps:
      - name: Prepare rbfx environment
        id: rbfx
        uses: rokups/rbfx-temp/.github/actions/ci-prepare-platform@rk/ci-reusable-workflow3
        with:
          profile: downstream
          framework_source: https://github.com/rokups/rbfx-temp.git#rk/ci-reusable-workflow3
          framework_build_type: sdk
          host_artifact_names: |
            sample-project-build-${{ matrix.ci_host_platform_tag }}
            rebelfork-sdk-${{ matrix.ci_host_platform }}-${{ matrix.ci_host_compiler }}-${{ matrix.ci_host_arch }}-dll-latest.7z

      - name: Build sample project
        uses: rokups/rbfx-temp/.github/actions/ci-build-project@rk/ci-reusable-workflow3
        with:
          android_dir: android
          artifact_name: sample-project-build-${{ matrix.ci_platform_tag }}
