name: Deploy
on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - master

permissions:
  actions: read
  contents: read

env:
  ci_source_dir: ${{ github.workspace }}/source-code
  ci_build_script: ./source-code/Script/ci_build.sh
  ci_web_build_dir: ${{ github.workspace }}/web-build
  ci_windows_build_dir: ${{ github.workspace }}/windows-build
  ci_target_sdk_dir: ${{ github.workspace }}/SDK-target

defaults:
  run:
    shell: bash

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.repository.full_name == 'rbfx/sample-project'

    steps:
      - name: Checkout Sample Project
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          path: source-code
          fetch-depth: 1
          submodules: true

      - name: Download web build artifact
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
          name: sample-project-build-web-emscripten-wasm-lib
          path: ${{ env.ci_web_build_dir }}

      - name: Download Windows build artifact
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ github.token }}
          repository: ${{ github.event.workflow_run.repository.full_name }}
          run-id: ${{ github.event.workflow_run.id }}
          name: sample-project-build-windows-msvc-x64-lib
          path: ${{ env.ci_windows_build_dir }}

      - name: Download Windows SDK
        uses: robinraju/release-downloader@v1.8
        with:
          repository: rbfx/rbfx
          tag: latest
          fileName: rebelfork-sdk-windows-msvc-x64-lib-latest.7z

      - name: Unzip Windows SDK
        run: |
          cd '${{ github.workspace }}'
          rm -rf '${{ env.ci_target_sdk_dir }}'
          7z x 'rebelfork-sdk-windows-msvc-x64-lib-latest.7z' '-o${{ github.workspace }}' -y
          mv './rebelfork-sdk-windows-msvc-x64-lib-latest' '${{ env.ci_target_sdk_dir }}'
          rm 'rebelfork-sdk-windows-msvc-x64-lib-latest.7z'

      - name: Prepare web package
        env:
          ci_platform: web
          ci_build_dir: ${{ env.ci_web_build_dir }}
          ci_build_mode: sdk
        run: ${{ env.ci_build_script }} prepare

      - name: Prepare Windows package
        env:
          ci_platform: windows
          ci_build_dir: ${{ env.ci_windows_build_dir }}
          ci_build_mode: sdk
        run: ${{ env.ci_build_script }} prepare

      - name: Set up butler
        uses: jdno/setup-butler@v1

      - name: Publish web build
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push "${{ env.ci_web_build_dir }}/bin/project" "eugeneko/sample-project:web"

      - name: Publish Windows build
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          butler push "${{ env.ci_windows_build_dir }}/bin/project" "eugeneko/sample-project:windows"
